//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForkBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection sBlocked {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sBlocked"]));
            }
            set {
                this["sBlocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string blockedWords {
            get {
                return ((string)(this["blockedWords"]));
            }
            set {
                this["blockedWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int jackpot {
            get {
                return ((int)(this["jackpot"]));
            }
            set {
                this["jackpot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int recordClaims {
            get {
                return ((int)(this["recordClaims"]));
            }
            set {
                this["recordClaims"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection warnedFMs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["warnedFMs"]));
            }
            set {
                this["warnedFMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastBid {
            get {
                return ((global::System.DateTime)(this["lastBid"]));
            }
            set {
                this["lastBid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>weedswell</string>
  <string>superwell</string>
  <string>santawell</string>
  <string>ragewell</string>
  <string>patswell</string>
  <string>mariowell</string>
  <string>luigiwell</string>
  <string>jerkswell</string>
  <string>goldswell</string>
  <string>eggswell</string>
  <string>batswell</string>
  <string>jattswell</string>
  <string>Ahegaoswell</string>
  <string>monkaSwell</string>
  <string>lennyswell</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection unclaimedMaxwells {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["unclaimedMaxwells"]));
            }
            set {
                this["unclaimedMaxwells"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\ForkDB.mdb")]
        public string ForkDBConnectionString {
            get {
                return ((string)(this["ForkDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection claimedMaxwells {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["claimedMaxwells"]));
            }
            set {
                this["claimedMaxwells"] = value;
            }
        }
    }
}
